[rule_set]
# Avoid complex flow constructs
restrict_goto = true
restrict_longjmp = true
restrict_setjmp = true
restrict_recursion = true

# Enforce loop bounds
fixed_loop_bounds = true

# Restrict the use of heap allocation, i.e. malloc, calloc, realloc, free
restrict_heap_allocation = true

# Enforce function size of no more than 60 lines
restrict_function_size = true

# Ensure that function calls always have a return value checked
check_return_value = true